apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
- serviceaccount.yaml
- envoy-configmap.yaml
- spiffe-helper-configmap.yaml
- deployment.yaml
- service.yaml

labels:
- pairs:
    app: backend
    component: spire-demo
