apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
- serviceaccount.yaml
- envoy-configmap.yaml
- deployment.yaml
- service.yaml

commonLabels:
  component: frontend
  pattern: envoy-sds
